source "https://rubygems.org"

group :test do
  gem "rake"
  gem "rspec"
  gem "puppet", ENV['PUPPET_VERSION'] || ENV['GEM_PUPPET_VERSION'] || ENV['PUPPET_GEM_VERSION'] || '~> 3.8'
  gem "facter", ENV['FACTER_VERSION'] || ENV['GEM_FACTER_VERSION'] || ENV['FACTER_GEM_VERSION'] || '~> 2.2.0'
  gem "rspec-puppet"
  gem "puppetlabs_spec_helper"
  gem "metadata-json-lint"
  gem "rspec-puppet-facts"
  gem "mocha"
  # Use puppet-catalog-test from git because last released gem 0.4.2 gives a deprecation
  # warning: "[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead."
  gem "puppet-catalog-test", :git => 'https://github.com/invadersmustdie/puppet-catalog-test.git', :ref => 'ac386793c2c456d2071dd0adda716224128f0bb3'
  gem "leap_cli", :git => 'https://leap.se/git/leap_cli.git'
end
