name    'erwbgy-check_mk'
version '0.3.0'
source 'https://github.com/erwbgy/puppet-check_mk.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'install and configure check_mk'
description 'Install and configure check_mk agent and Nagios plugin'
project_page 'https://github.com/erwbgy/puppet-check_mk'
dependency 'puppetlabs/stdlib', '>= 2.6.0'
dependency 'ripienaar/concat', '>= 0.2.0'
